# nixpacks.toml

# Menentukan bahwa ini adalah proyek PHP
providers = ["php"]

[phases.setup]
# Meminta Railway untuk menginstal paket PHP dan ekstensi FPM
nixPkgs = ["pkgs.php82", "pkgs.php82Extensions.fpm"]

[start]
# Perintah ini akan dijalankan oleh Procfile
cmd = "vendor/bin/heroku-php-apache2 public/"